# 1. DISABILITA DC-DC (Risolve il crash della radio sui cloni SuperMini privi di induttanze)
CONFIG_BOARD_ENABLE_DCDC=n
CONFIG_BOARD_ENABLE_DCDC_HV=n

# 2. POTENZA TRASMISSIONE BLUETOOTH AL MASSIMO (+8 dBm per antenne cloni)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 3. IMPOSTAZIONI ZMK STUDIO E BATTERIA
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_BATTERY_REPORTING=y

# 4. DISABILITA IL DEEP SLEEP TEMPORANEAMENTE PER IL TEST
# (Evita che il pad si spenga subito mentre facciamo le prove)
CONFIG_ZMK_SLEEP=n
